package method

var httpMethods = []string{
	"GET", "POST", "PUT", "DELETE", "OPTIONS", "HEAD", "PATCH", "TRACE",
	"CONNECT", "COPY", "LOCK", "MKCOL", "MOVE", "PROPFIND", "PROPPATCH",
	"UNLOCK", "CHECKIN", "CHECKOUT", "LABEL", "MERGE", "REPORT", "UPDATE",
	"ACL", "BASELINE-CONTROL", "MKACTIVITY", "MKWORKSPACE", "ORDERPATCH",
	"SEARCH", "UNCHECKOUT", "VERSION-CONTROL",
}
